Repository open-sauced/open-sauced, pull requests merged in 2020-06, with the labels that each got.

#581 Trim whitespace while adding the repo
  package-lock.json
  src/components/AddRepoForm.js
  src/components/ListGoals.js
  src/components/RepoListItem.js
  src/tests/util.test.js
Labels: bug

#591 Add humanize number
  package-lock.json
  src/components/Repository.js
  src/lib/humanizeNumber.js
  src/lib/humanizeNumber.test.js
Labels: enhancement

#590 472 leverage textarea
  src/components/NoteForm.js
  src/styles/Note.js
  src/styles/TextArea.js
Labels: bug

#598 525 page reload with cached login
  src/components/Nav.js
  src/containers/App.js
  src/hoc/AuthHOC.js
  src/index.js
Labels: bug, enhancement

#601 Add total users count in adminstats bar
  package-lock.json
  src/components/AdminStatsBar.js
  src/lib/apiGraphQL.js
Labels: enhancement

#602 404 page
  package-lock.json
  src/components/Hero.js
  src/containers/App.js
  src/images/404.svg
  src/images/index.js
  src/styles/NotFound.js
  src/styles/variables.js
Labels: enhancement

#604 Correct a typo
  README.md
Labels: documentation

#605 Improve release-drafter.yml
  .github/release-drafter.yml
  CONTRIBUTING.md
Labels: chore

#606 Add documentation label to the release-drafter.yml template
  .github/release-drafter.yml
Labels: chore

#619 patch/v0.14.2
  package-lock.json
  package.json
Labels: patch

#609 Add an empty placeholder for goals
  package-lock.json
  src/components/Issues.js
  src/components/RepositoryGoals.js
  src/styles/EmptyPlaceholder.js
Labels: enhancement, minor

#622 Admin bar will not show when logged out
  package-lock.json
  src/index.js
Labels: bug, patch

#624 User can now delete the note entirely
  src/components/NoteForm.js
Labels: bug

#625 Add spinner for contributions
  src/components/Contributions.js
  src/styles/Spinner.js
Labels: enhancement

#629 Update homepage.png
  src/images/homepage.png
Labels: documentation

#630 Correct notes scrolling bar
  src/styles/TextArea.js
Labels: bug

#635 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#628 fix: grammar & typos
  CODE_OF_CONDUCT.md
Labels: chore, documentation

#633 Add badges in README
  README.md
Labels: chore, documentation

#634 Add a link to GitHub search for users in the admin bar
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/release-management.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  package-lock.json
  src/components/AdminStatsBar.js
  src/components/Contributions.js
  src/images/homepage.png
  src/index.js
  src/styles/Spinner.js
  src/styles/TextArea.js
Labels: enhancement

#637 Create TRIAGE_GUIDE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  TRIAGE_GUIDE.md
Labels: chore

#642 Fixed Quote Author's Name Issue
  package-lock.json
  src/styles/Header/Hero.js
Labels: bug

#644 Added Emojis to Issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#646 add rel=noreferrer to all target="_blank"
  CONTRIBUTING.md
  src/components/AdminStatsBar.js
  src/components/Contributions.js
  src/components/Hero.js
  src/components/Issues.js
  src/components/Nav.js
  src/components/Repository.js
  src/components/RepositoryGoals.js
  src/containers/App.js
  stories/4-Nav.stories.js
Labels: chore

#648 Add lighthouse.yml
  .github/workflows/lighthouse.yml
Labels: enhancement

#657 Feature: lint action
  .github/workflows/lint.yml
Labels: enhancement

#664 Fix hero details columns
  src/components/Hero.js
  src/styles/Grid/GridColumns.js
  src/styles/Grid/index.js
  src/styles/Header/Hero.js
Labels: bug

#670 Update the discord invitation line
  CONTRIBUTING.md
  README.md
Labels: chore, documentation

#662 Add linguist details in repo page
  src/components/Repository.js
  src/lib/apiGraphQL.js
  src/styles/Card.js
Labels: 🍕 enhancement, 💡 feature

#674 Remove unused classes and components
  src/components/Instructions.js
  src/components/Repository.js
  src/components/RepositoryGoals.js
  src/tests/Instructions.test.js
Labels: chore

#666 526 set stars with new repo meta data
  package-lock.json
  package.json
  src/components/ListGoals.js
  src/components/RepoListItem.js
  src/components/RepositoryGoals.js
  src/lib/apiGraphQL.js
  src/styles/Grid/Flex.js
  src/styles/Grid/index.js
  src/tests/mocks/data.js
Labels: 🍕 enhancement

#672 PWA Implementation
  public/icon-144x144.png
  public/icon-192x192.png
  public/icon-72x72.png
  public/icon-96x96.png
  public/index.html
  public/manifest.json
Labels: 🍕 enhancement

#683 Add number of languages as a const
  src/components/Repository.js
  src/components/RepositoryGoals.js
Labels: chore

#686 Update labels in issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: chore

#698 prevents audit CI until netlify completes
  .github/workflows/lighthouse.yml
Labels: chore

#694 Rename logo1 to logo
  src/components/Hero.js
  src/components/Nav.js
  src/logos/index.js
  src/logos/logo.svg
  stories/4-Nav.stories.js
  stories/6-Home.stories.js
Labels: 🍕 enhancement

#702 Open Sauced name on browser console
  src/containers/App.js
  src/index.js
Labels: 💡 feature

#695 Add truncate util
  src/components/RepoListItem.js
  src/lib/humanizeNumber.test.js
  src/lib/truncate.js
  src/lib/truncate.test.js
Labels: 🍕 enhancement, 🐛 bug

#711 Plural/singular of words
  src/components/IssueListItem.js
  src/components/Repository.js
Labels: patch, 🍕 enhancement

#720 First PR considerations
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
Labels: 📝 documentation

#723 Add placeholder and PR count if issues are disabled
  src/components/Issues.js
  src/components/Repository.js
  src/lib/apiGraphQL.js
Labels: 🍕 enhancement, 🐛 bug

#692 Remove unused assets and code
  src/components/sauce-anchor.svg
  src/fonts/icomoon.eot
  src/fonts/icomoon.svg
  src/fonts/icomoon.ttf
  src/fonts/icomoon.woff
  src/images/full-sauce.svg
  src/images/index.js
  src/images/one.jpeg
  src/images/sauce2.svg
  src/logos/index.js
  src/logos/logo2.svg
  src/logos/logo3.svg
  src/logos/logo4.svg
  src/logos/logo5.svg
  src/logos/logo6.svg
  src/logos/logo7.svg
  src/logos/logo8.svg
Labels: 🍕 enhancement

#678 Change homepage screenshot
  src/images/homepage.png
Labels: chore, 🍕 enhancement

#729 Add "sync in progress" in star's placeholder
  src/components/RepoListItem.js
Labels: 🍕 enhancement, 💡 feature

#728 Add repo check validation
  package-lock.json
  src/components/AddRepoForm.js
  src/lib/repoStatusCode.js
  src/lib/repoStatusCode.test.js
Labels: 🐛 bug

#735 Add license in repo meta card
  src/components/Repository.js
  src/lib/apiGraphQL.js
Labels: 💡 feature

#733 Add repo description in context box
  src/components/Repository.js
  src/lib/apiGraphQL.js
Labels: 💡 feature

#738 Updated Favicon
  package-lock.json
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  src/components/AddRepoForm.js
  src/lib/repoStatusCode.js
  src/lib/repoStatusCode.test.js
Labels: 🍕 enhancement

#726 Fixed blank dashboard page caused by null values
  src/components/RepositoryGoals.js
Labels: 🐛 bug

#741 Added Repo Icon in Context Box
  src/components/Repository.js
  src/components/RepositoryGoals.js
  src/styles/RepositoryAvatar.js
Labels: 💡 feature

#748 Revert note contents on cancel to last saved version
  package-lock.json
  package.json
  src/components/NoteForm.js
  src/tests/NoteForm.test.js
Labels: 🐛 bug

#747 Set local react state to avoid requests happening
  src/index.js
Labels: 🐛 bug

#749 Feature: Icons moved to Octicons v10.0.0
  package-lock.json
  package.json
  src/components/DetailInfo.js
  src/components/IssueListItem.js
  src/components/Issues.js
  src/components/NoteForm.js
  src/components/RepoListItem.js
  src/components/Repository.js
  src/components/RepositoryGoals.js
Labels: chore

#751 Correct the font on 404
  src/styles/NotFound.js
Labels: 🍕 enhancement, 🐛 bug
