Repository open-sauced/open-sauced, pull requests merged in 2020-05, with the labels that each got.

#546 New homepage
  src/components/Hero.js
  src/components/IssueListItem.js
  src/components/RepositoryGoals.js
  src/index.css
  src/lib/apiGraphQL.js
  src/styles/Card.js
  src/styles/Header/Hero.js
  src/styles/Header/index.js
  src/styles/Spinner.js
Labels: enhancement, in-progress

#559 Better README
  README.md
Labels: documentation, enhancement

#561 Issues empty placeholder
  package-lock.json
  src/components/Issues.js
  src/styles/EmptyPlaceholder.js
Labels: enhancement

#565 Add cancel button
  src/components/NoteForm.js
Labels: enhancement

#562 Better list
  package-lock.json
  package.json
  src/components/Contributions.js
  src/components/IssueListItem.js
  src/components/Issues.js
  src/lib/apiGraphQL.js
  src/styles/Card.js
  src/styles/List.js
Labels: enhancement

#583 Add discord link and links trusted section logos
  README.md
  src/components/Hero.js
  src/components/Nav.js
Labels: documentation, enhancement

#584 (redo) Adds links to trusted section images
  package-lock.json
  src/components/Hero.js
  src/components/Nav.js
Labels: enhancement

#582 AdminStats Bar Implementation
  package-lock.json
  package.json
  src/components/AdminStatsBar.js
  src/components/Nav.js
  src/containers/App.js
  src/index.js
  src/lib/apiGraphQL.js
  src/styles/Header/AdminNav.js
  src/styles/Header/index.js
  src/styles/variables.js
  src/tests/AdminStatsBar.test.js
  src/tests/mocks/location.js
Labels: enhancement, feature
