Repository open-sauced/open-sauced, pull requests merged in 2020-07, with the labels that each got.

#755 Resolves #754: centered logo across browsers
  src/components/Nav.js
  src/styles/Grid/Float.js
  src/styles/Grid/index.js
Labels: 🐛 bug

#763 Set color of text based on contrast
  package-lock.json
  package.json
  src/components/IssueListItem.js
Labels: 🐛 bug

#764 Add fork and go to fork buttons
  src/components/Repository.js
  src/lib/apiGraphQL.js
  src/tests/Repository.test.js
Labels: 💡 feature

#768 Add a workflow to welcome new contributors
  .github/workflows/welcome.yml
Labels: 💡 feature

#765 Filter and Sort Goals by name and stars
  package-lock.json
  src/components/AddRepoForm.js
  src/components/ListGoals.js
  src/components/RepoListItem.js
  src/icons/index.js
  src/icons/search.svg
  src/styles/Search.js
  src/styles/Select.js
Labels: 💡 feature

#771 Show fork if the user is not the owner
  src/components/Repository.js
  src/tests/Repository.test.js
Labels: 🐛 bug

#753 Skeleton Loading instead of "Loading..."
  package-lock.json
  package.json
  src/components/Contributions.js
  src/components/DetailInfo.js
  src/components/Issues.js
  src/components/IssuesLoader.js
  src/components/Repository.js
  src/styles/Card.js
  src/styles/List.js
  src/styles/Loader.js
  src/tests/Contributions.test.js
Labels: 🍕 enhancement

#780 updates the broken release.yml labels
  .github/release-drafter.yml
Labels: chore

#784 Fix fork button
  package-lock.json
  src/components/Repository.js
Labels: 🐛 bug

#785 Add test for 301 status in repoStatusCode.test.js
  src/lib/repoStatusCode.js
  src/lib/repoStatusCode.test.js
Labels: testing

#781 Add required params
  src/containers/App.js
Labels: 🐛 bug

#792 [STYLE] Updated button styles
  src/styles/Button.js
Labels: patch, 🍕 enhancement
