Repository open-sauced/open-sauced, pull requests merged in 2021-05, with the labels that each got.

#970 refactor: change wording from "delete" to "remove"
  src/components/DangerZone.js
  src/styles/Backdrop.js
Labels: 🐛 bug

#975 fix: able to add the same repo twice
  src/components/AddRepoForm.js
  src/components/RepositoryGoals.js
Labels: 🐛 bug

#969 feat: filter issues by labels
  src/components/Issues.js
  src/lib/persistedGraphQL.js
Labels: minor, 💡 feature

#973 refactor: Cleanup graphql
  src/components/Contributions.js
  src/components/Issues.js
  src/components/Repository.js
  src/lib/apiGraphQL.js
  src/lib/persistedGraphQL.js
Labels: minor

#1008 fix: Release note tagging
  .github/release-notes.yml
Labels: minor

#1009 feat: Bye Bye Release Drafter
  .github/release-notes.yml
  .github/workflows/ci.yml
  .github/workflows/release-management.yml
  package.json
Labels: minor

#963 feat: 344 persisted fetch viewer stars
  package-lock.json
  src/components/ListGoals.js
  src/components/RecommendedRepoList.js
  src/components/Repository.js
  src/components/RepositoryGoals.js
  src/icons/plus.svg
  src/lib/apiGraphQL.js
  src/lib/persistedGraphQL.js
  src/styles/Avatar.js
  src/styles/Card.js
  stories/2-Card.stories.js
Labels: 🍕 enhancement, 💡 feature
