Repository open-sauced/open-sauced, pull requests merged in 2021-04, with the labels that each got.

#933 feat: Organize GitHub Actions ci.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lighthouse.yml
  .github/workflows/lint-pr.yml
  .github/workflows/pr-audit-target.yml
  .github/workflows/release-management.yml
  .github/workflows/welcome.yml
Labels: minor

#938 feat: Adding new Trust Icons
  src/components/Hero.js
  src/images/UseShoppingCart.png
  src/images/electron.png
  src/images/gitTrends.svg
  src/images/go.png
  src/images/index.js
  src/images/next.png
  src/images/remirror.png
  src/images/remirror.svg
  src/styles/Header/Hero.js
Labels: minor

#942 ci: Freeze the lockfile in CI
  .github/workflows/ci.yml
Labels: minor, 🍕 enhancement

#943 chore: Update the caniuse database
  package-lock.json
Labels: dependencies

#959 feat: adds persisted query for issues by labels.
  src/lib/apiGraphQL.js
  src/lib/persistedGraphQL.js
Labels: 💡 feature
